### ISSUE TITLE
webview problems or whatever. 

### ISSUE THREAD

**Issue by Glazami** [flamegapps/flamegapps#2]
I use the full version, the main pages of stores do not open in the aliexpress application, everything works through a third-party browser, but it is through the webview inside the application that aliexpress does not work, and delays and thoughtfulness in all applications, pages open with a noticeable delay, I tried to collect a full-fledged log but me a device without root rights. and limited logs only indicate errors, but do not indicate a specific scenario. This has been happening for half a year.

**Comment by ayandebnath** [comment]
I don't think this is related to web view. Also, FlameGApps doesn't carry aosp/google web view inside the main gapps file. But you can try the Google Web View addon by us. Please let us know what happens.

**Comment by Glazami** [comment]
Do I just have to install the zip file using the recovery menu?

**Comment by ayandebnath** [comment]
Yes.

**Comment by Glazami** [comment]
Before installing the add-on and after it is the same. 
![photo_2021-07-18_00-15-29](https://user-images.githubusercontent.com/65298911/126048466-2ea4eceb-5f3c-47b9-bcd9-b70eb3ccccf1.jpg)
![photo_2021-07-18_00-15-28](https://user-images.githubusercontent.com/65298911/126048468-568b5c08-aaf2-48fa-9431-661ec71c225c.jpg)
but after installation the waiting time is longer

**Comment by Glazami** [comment]
I see these messages for half a year, in all the stores I go to. also sometimes a long page load in tiktok despite a good internet connection.

**Comment by Glazami** [comment]
I also tried all versions of the webview from the play market, be it alpha or beta version.

**Comment by ayandebnath** [comment]
Maybe the issue is in your ROM or device tree. Contact maintainer(s)

**Comment by Glazami** [comment]
I have repeatedly contacted the maintainer and sent him logs, there are no problems with the firmware.

**Comment by ayandebnath** [comment]
Try a different ROM.
