### ISSUE TITLE
Apps hanging after flashing on LOS 19

### ISSUE THREAD

**Issue by francoism90** [flamegapps/flamegapps#5]
I've tried using the core/full package (latest build), but for some reason, apps (even just Settings) keep freezing after installing this on my LOS 19.

If I remove your or any GAPPS package, the problem goes away.

Do you have any idea? Thanks.

**Comment by ayandebnath** [comment]
Android version?

**Comment by francoism90** [comment]
Android 12

**Comment by ayandebnath** [comment]
Try changing ROM, if still happens change the GApps and let me know.

**Comment by francoism90** [comment]
@ayandebnath It does work fine with ArrowOS 12 (Android 12).

I just would like to know how to potentially solve it. :)

**Comment by ayandebnath** [comment]
As far as I know, GApps (and even other apps) are not responsible for freezing, this is basically related to the ROM/DT.

**Comment by francoism90** [comment]
@ayandebnath Yeah, I do this is a ROM issue. However I would like to know how to solve it.

**Comment by ayandebnath** [comment]
👍️

**Comment by francoism90** [comment]
@ayandebnath Here is my [logcat](https://drive.google.com/file/d/1yXCnzF5X_qkhcDgrTyfEStsw8PYAOBDY/view?usp=sharing)

Think it's a permission issue?

**Comment by ayandebnath** [comment]
Don't know.

**Comment by francoism90** [comment]
@ayandebnath I don't know either, giving up and going back to LOS 18 for now. :/
